version: '3.5'
services:
  web:
    build: .
    scale: 1
    cpus: 0.4
    mem_limit: 128m
    expose:
      - "3001"
    command: npm run start
    environment:
      - CLUSTERING_ENABLED=false
      - PORT=3001

  nginx:
    mem_limit: 128m
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "3000:3000"
